version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: url_shortner_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
    name: url_shortner_redis_data
